### ISSUE TITLE
website is down (error 522)

### ISSUE THREAD

**Issue by slime73** [love2d/website#11]
The homepage, wiki, forums, etc. have all been down for the past while. I'm getting error 522 on Cloudflare's error page (with a link to some [support info](https://support.cloudflare.com/hc/en-us/articles/115003011431-Error-522#522error)).

**Comment by TheLinx** [comment]
The server was affected by a big issue in the datacenter where it's hosted: https://status.scaleway.com/incidents/jtw3cwktbry7

They say it's resolved but my server is one of those "anomalies" that requires additional assistance from support.

There must be a lot of people with higher support priorities needing help because I've been waiting ever since the last update on that incident.

(Also, I didn't notice this issue because my email went down with the server so I didn't get a notification)

**Comment by slime73** [comment]
I wonder if they forgot about us...

**Comment by TheLinx** [comment]
Unfortunately the downtime will continue.

> Hello,
> 
> Following the incident reported here: https://status.scaleway.com/incidents/jtw3cwktbry7, we regret to inform you that we are
> unable to restart certain servers, neither in rescue, nor in normal mode.
> This unfortunately means that the data on these servers cannot be recovered.
> 
> Our teams are already working on issuing refunds for the month of February for server rental which will no longer be able
> to be fulfilled for the full month. This refund will be made via the payment method saved to your account over the next few weeks.
> 
> In order to avoid future invoicing for these servers, we will be placing them as withdrawn from service on 31/03/2022.
> Please note that any Dedibackup servicelinked to these servers will be stopped at the same time.
> We therefore invite you to retrieve any data that you may have placed in Dedibackup before 31/03/2022.
> 
> An alternative to this is to upgrade your server, meaning a new server would be deployed on your account (subject to availability).
> No installation fees will be incurred for this service. Should you wish to proceed in this manner,
> please respond to indicate the replacement server of your choice.
> Please note that the main IP address of the server cannot be moved to another Dedibox.
> 
> Should you have any questions, please do not hesitate to respond to us via ticket.
> 
> We sincerely apologize for this incident, and our team remains available to provide you with further information.
> The Scaleway team.

I do have backups but I will need time to set up a new server.

**Comment by gcmartijn** [comment]
> I do have backups but I will need time to set up a new server.
Nice, most people don't have backups.

**Comment by slime73** [comment]
Yikes :(

**Comment by TheLinx** [comment]
Things are back up now. It may still be a little bit unstable for a bit while I'm setting up some other things.

Let me know if anything has stopped working.

edit: I noticed the large files are missing. That's just because I accidentally copied them into the wrong folder. They're going to be working soon.

**Comment by slime73** [comment]
Thanks for dealing with this so quickly (and for having backups)!
