### ISSUE TITLE
can't register to the forum using a gmail account

### ISSUE THREAD

**Issue by candardo** [love2d/website#14]
I couldn't register to the forum with my personal gmail account. I also tried with another Google Suite account from work and failed.
What happens:
- I choose an username and password, fill in email address and anti-bot form
- the account is created and the confirmation email should be sent
- I get no email even after days
- I check spam and any other folder
- I request another confirmation email
- I write to the forum administrator using the form and get no response
- I register with another email account and all is fine
Then I report the problem in the forum and on discord where people point me here. 

Could it be gmail _blackholing_ love2d mails?

**Comment by TheLinx** [comment]
Thank you bringing this to my attention. My outgoing email was not set up correctly.
I've done thorough testing now and GMail (and other email providers) should accept forum emails again.

**Comment by candardo** [comment]
I've just tried activating my inactive (not verified) forum account and I still don't get any email clicking the "Resend activation email" link. 

Anyway if it was just some server setup problem how could I register just using a different email account?

**Comment by TheLinx** [comment]
Spam filtering at scale is not an exact science. What is true is that outgoing emails were not good, and now they are.
By not good I mean that they looked suspicious to spam filters.

The different treatment could be because of differences between providers, or if they were both gmail accounts, pure chance?
If you're sure that you've typed the email correctly for the inactive user maybe wait a day and try again. It could be a cached result (aka a grudge) by the spam filter that prevents further emails from arriving.

If you'd like me to take a closer look, send an email to thelinx@unreliablepollution.net with your forum username and email address and I can take a look.

**Comment by candardo** [comment]
Thanks! I'm fine since I already got an account so I'm fine (maybe I'll swap the email contact later).
